apiVersion: v1
kind: ServiceAccount
metadata:
  name: xmb-api
  namespace: psp-xmb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xmb-api-game-session
  namespace: psp-xmb
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["game-session"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    resourceNames: ["game-session"]
    verbs: ["get", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xmb-api-game-session
  namespace: psp-xmb
subjects:
  - kind: ServiceAccount
    name: xmb-api
    namespace: psp-xmb
roleRef:
  kind: Role
  name: xmb-api-game-session
  apiGroup: rbac.authorization.k8s.io
